baseURL = 'https://preview.muc-uke.de/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-scroll'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true


# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

[params]
    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "© Frank Mattheus"

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Munich Ukulele Collective"

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and
    # https://gohugo.io/templates/internal#open-graph.
    images = ["images/cover-image.jpg"]

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Munich Ukulele Collective"

    # This theme will, by default, inject a design-by-line at the bottom of the page.
    # You can turn it off, but we would really appreciate if you don’t :-)
    # hidedesignbyline = true

    [params.meta]
        keywords = "Munich, ukulele, collective, open, mic, karaoke"

[languages]
  [languages.en]
    contentDir = 'content/english'
    languageName = 'English'
    languageNameShort = "en"
    languageFlag = "🇬🇧"
    languageImage = "/images/EN.png"
    weight = 10
    title = 'My site'
  [languages.de]
    contentDir = 'content/deutsch'
    languageName = 'Deutsch'
    languageNameShort = "de"
    languageFlag = "🇩🇪"
    languageImage = "/images/DE.png"
    weight = 20
    title = 'Meine Seite'
